name: SQLCipher Performance
on: [ push ]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "* SQLCipher Performance Build & Test *"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Check for vulnerabilities
        run: ./gradlew dependencyCheckAnalyze


